[package]
name = "openviking-memory"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
openagent-pdk = { path = "../../../openagent-go/plugin/pdk/rust" }
openviking-common = { path = "../openviking-common" }
serde = { version = "1", default-features = false, features = ["derive"] }
