[package]
name = "hdspace-renew-v2"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
openagent-pdk = { git = "https://github.com/yusheng-g/openagent-go", subdirectory = "plugin/pdk/rust" }
hdspace-common = { path = "../hdspace-common" }
serde = { version = "1", default-features = false, features = ["derive"] }
